### ISSUE TITLE
feat(service): use of signal

### ISSUE THREAD

**Issue by rbalet** [ngx-translate/core#1532]
## Current behavior
We need to be working with subscription.

## Expected behavior
Although this is good the way it is, it could be nicer to add additional signal alternative.

## What is the motivation / use case for changing the behavior?
1. It would let us work with `computed` variable directly
2. It will lower the chances of forgotten unsubscription 

## How do you think that we should implement this?
_I can do a PR if needed_

I do see two options
### 1: Additional variable
Inside the `translate.service.ts`, add of additional signal for reach observable

```typescript
// Exemple

  $onTranslationChange = toSignal(this.store.onTranslationChange)
  get onTranslationChange(): Observable<TranslationChangeEvent> {
    return this.store.onTranslationChange;
  }
```

### 2: Replacement of the former logic 
_I'd avoid this as this is quite a breaking change_

Same as 1. but we remove the `onTranslationChange()` method. which let you write it as follow. 
```typescript
onTranslationChange = toSignal(this.store.onTranslationChange)
```

_I do personally always use the `$` in front of a signal, but standards aren't set yet for the nomenclature_

**Comment by nxnen8282** [comment]
Our system attempted to address this issue:

Added signal alternatives for translation change events while maintaining existing Observable API. This allows working with computed variables directly and reduces chances of forgotten unsubscriptions.

Changes:
- Added imports for signal-related functionality
- Added signal alternatives with $ prefix for translation change events
- Maintained existing Observable-based API

You can examine the suggested modifications here: https://github.com/nxnen8282/ngx-translate-core-1532/commit/36bdf132967a597bf14521e494c9d3a60e7d1319.


> [!CAUTION]
> Advisory: This solution was generated using automated tools, and we strongly recommend reviewing the code thoroughly before implementation. The solution may be partial - please consider it as inspiration for your own implementation.

**Comment by floAtEbcont** [comment]
@rbalet You only addressed `onTranslationChange`, but to be consistent, I think `get()` should have a signal equivalent too - here's a sample that works for me:

```typescript
translate(
        key: string | Signal<string>,
        params?: Record<string, string | number | null | undefined> | Signal<Record<string, string | number | null | undefined> | undefined>,
    ): Signal<string | undefined> {
        const key$ = toObservable(isSignal(key) ? key : signal(key));
        const params$ = toObservable(isSignal(params) ? params : signal(params));

        const translation$ = key$.pipe(switchMap((key) => params$.pipe(switchMap((params) => this.get(key, params)))));

        return toSignal(translation$);
 }
```

This can than be used like this for example:

```typescript
class MyComponent {
  readonly amount = computed(() => this.someComputation());
  readonly someReactiveTranslation = this.translateService.translate('myKey', computed(() => ({
    amount: this.amount()
  }));
}
```

**Comment by rbalet** [comment]
@floAtEbcont yes indeed, every method would have their equivalent.

It was just for the sake of simplicity

**Comment by homj** [comment]
Thank you for opening this issue @rbalet. Signals are essential for modern angular development and should be supported by ngx-translate asap.

This should also extend to actual translation. I propose to add a method similar to `stream`, that returns a signal which reacts on lang or translation change. We could simply call this method `translate`

**Comment by rbalet** [comment]
@homj it is true that, if you add the `$` in front of the variable, you could not need the `on...Change` as it is per syntax already understandable

**Comment by floAtEbcont** [comment]
@homj 

> This should also extend to actual translation. I propose to add a method similar to stream, that returns a signal which reacts on lang or translation change. We could simply call this method translate

This is exactly what I did [further up](https://github.com/ngx-translate/core/issues/1532#issuecomment-2729044551), right?

**Comment by EinfachHans** [comment]
@rbalet is there a target branch for v18 already? I'm considering working on a PR for that.
Any additional informations/hints you would like to place for the implementation?

**Comment by rbalet** [comment]
Hey @EinfachHans, thanks for the proposition.

We're sadly on pause till we find the best solution for the following discussion: https://github.com/ngx-translate/core/discussions/1599

So I wouldn't invest much time till we get done with it. 
But I'll text you back once we could make a stable version.

Don't hesitate to take part of the discussion, all the help are always welcome

**Comment by CodeAndWeb** [comment]
`onTranslationChange()` and `use()` will not be able to provide translations anymore through the observable.
This is because we won't have a combined store that contains all translations.
So it would practically only be `bool` or `void` - just to inform the users about the change. 

Adding that `translate()` signal sounds good for me - how ever it's not sufficient like in the implementation by @floAtEbcont it should also recalculate on `onLangChange`, `onTranslationChange` and `onFallbackLangChange` .

Introducing a combined observable for all of these 3 would make sense and simplify the code.

**Comment by rbalet** [comment]
@CodeAndWeb   
Linked proposition : https://github.com/ngx-translate/core/tree/feat/signals

Note:
-  I have not yet implemented the tests as I'd prefer being sure about this new implementation before moving forward
- I'm Also, wondering how much sens it'll make as the older way of doing will mostly be deprecated
- When we're honest, maybe it's better to drop the backward compatibility as we both have not that much time to maintain it  _(But if wished I will invest the required time)_

@homj Care to do your stream approach on my PR ? 
@EinfachHans Would you be open to give it a look, what do you think of this implementation ? _(I'm open to any suggestion)_
@floAtEbcont I did change every observable andalso the get. Let me know what you think or if you see something's missing

**Comment by CodeAndWeb** [comment]
I see how signals work for simple state management. 

I wonder how we could merge the results of multiple http requests using signals in a simple way.

**Comment by EinfachHans** [comment]
Maybe i missed it, but it would be great to have a function (similar to `get`) which returns a signal, which will be automatically updated when the translation or language has changed

**Comment by rbalet** [comment]
@EinfachHans There isn't need for `get` function anymore, just use the variable directly with a computed or an effect and enjoy the new way of working

```typescript
readonly translateService = inject(TranslateService)

$onLangChange = effect(() => { 
  const lang = translateService.$currentLang();

  console.log(lang); // Do whatever you'd like with it ;) 
});

translation = {
  de: 'Ich bin',
  fr: 'Je suis'
}

$translationString = computed(() => {
  return translation[translateService.$currentLang()];
});

$currentLang = translateService.$currentLang.asReadonly();
```

If we wish to go in this directly, I'll update the documentation to reflect real use

**Comment by rbalet** [comment]
> I see how signals work for simple state management.
> 
> I wonder how we could merge the results of multiple http requests using signals in a simple way.

@CodeAndWeb Yes we could, as in the latest angular version, signal accept signals ; )  
_I never did it though, but I can search and propose, let me know_

**Comment by EinfachHans** [comment]
@rbalet i would prefer a utility function directly from the library, something like:

```ts
const translateService = inject(TranslateService);

const signalTranslation = getSignal('some.key', { // params });
```

i guess otherwise every project will have to create this on their own with the same boilerplate code?

**Comment by rbalet** [comment]
@EinfachHans I've already converted each function to be working with the signals, so both are working out of the box.

- getTranslations(language: string)
- getTranslation(key)

But they're returning a values/objects and not signals. 

----
What I understand from you wish, is that `getSignal` returns a signal which is going to reflect the actual state of the targeted key.     
I'm not sure if it's a good idea, shall we open a discussion about it ? 

My point is, to do so each key will need to be a signal.   
If you add 1000 words, then you're instantiating 1000 signals.   

It could(will) have huge consequences on the optimisation end.  _(To be analyzed)_
But, was that even possible in the former version of ngx-translate?  

If that isn't the case, could you please open a new issue and clarify there, as good as possible, what you'd really like, and also the why ?

**Comment by EinfachHans** [comment]
Hey @rbalet ,

why needs every key a signal to do that?

I think of a helper function, that internally creates a `computed`. Internally that computed should work with the existent signals (lang and translation) and use the key, params that are passed into.

That would replace the boilerplate doing it everywhere ourself.

Similiar to [transloco](https://jsverse.gitbook.io/transloco/core-concepts/signals)

**Comment by floAtEbcont** [comment]
@rbalet 

> What I understand from you wish, is that getSignal returns a signal which is going to reflect the actual state of the targeted key.
I'm not sure if it's a good idea, shall we open a discussion about it ?

Yeah, I would wish for this too. And of top of that I would like to be able to use signals as interpolation params.

> If you add 1000 words, then you're instantiating 1000 signals.

Only for those translations you want to react to changes automatically. (I think no one is proposing to get rid of `instant()` for non-reactive contexts - that would be quite the breaking change.) 
And so far these reactive translations had to use `get()` which meant a 1000 observables for a 1000 words, which I think was _worse_ performance-wise.

Also, in fact, by now we are using [my above sample wrapper code](https://github.com/ngx-translate/core/issues/1532#issuecomment-2729044551) in production and haven't experienced any performance issues with it. (And that's even though it's producing the original ngx-translate observable _plus_ a signal per translation. However, I have to admit, we never need to translate huge amounts of texts reactively at the same time - we use virtual scrolling to avoid having too many components instantiated at the same time.)

**Comment by CodeAndWeb** [comment]
> [@EinfachHans](https://github.com/EinfachHans) There isn't need for `get` function anymore, just use the variable directly with a computed or an effect and enjoy the new way of working
> 
> readonly translateService = inject(TranslateService)
> 
> $onLangChange = effect(() => { 
>   const lang = translateService.$currentLang();
> 
>   console.log(lang); // Do whatever you'd like with it ;) 
> });
> 
> translation = {
>   de: 'Ich bin',
>   fr: 'Je suis'
> }
> 
> $translationString = computed(() => {
>   return translation[translateService.$currentLang()];
> });
> 
> $currentLang = translateService.$currentLang.asReadonly();
> If we wish to go in this directly, I'll update the documentation to reflect real use

This is not how it should work. I don't want the users to request all translations.
With this, there's no interpolation.

**Comment by CodeAndWeb** [comment]
> [@EinfachHans](https://github.com/EinfachHans) I've already converted each function to be working with the signals, so both are working out of the box.
> 
> * getTranslations(language: string)
> * getTranslation(key)
> 
> But they're returning a values/objects and not signals.
> 
> What I understand from you wish, is that `getSignal` returns a signal which is going to reflect the actual state of the targeted key. I'm not sure if it's a good idea, shall we open a discussion about it ?
> 
> My point is, to do so each key will need to be a signal. If you add 1000 words, then you're instantiating 1000 signals.
> 
> It could(will) have huge consequences on the optimisation end. _(To be analyzed)_ But, was that even possible in the former version of ngx-translate?
> 
> If that isn't the case, could you please open a new issue and clarify there, as good as possible, what you'd really like, and also the why ?

This is what `stream()`, the translate pipe and translate directive already do.
Currently, the pipe & directive subscribe to 3 different signals. (langChange, fallbackLangChange and translationChange).

**Comment by rbalet** [comment]
> > [@EinfachHans](https://github.com/EinfachHans) There isn't need for `get` function anymore, just use the variable directly with a computed or an effect and enjoy the new way of working
> > readonly translateService = inject(TranslateService)
> > $onLangChange = effect(() => {
> > const lang = translateService.$currentLang();
> > console.log(lang); // Do whatever you'd like with it ;)
> > });
> > translation = {
> > de: 'Ich bin',
> > fr: 'Je suis'
> > }
> > $translationString = computed(() => {
> > return translation[translateService.$currentLang()];
> > });
> > $currentLang = translateService.$currentLang.asReadonly();
> > If we wish to go in this directly, I'll update the documentation to reflect real use
> 
> This is not how it should work. I don't want the users to request all translations. With this, there's no interpolation.

@CodeAndWeb I see, not sure though how to implement it propelry : /

**Comment by rbalet** [comment]
> > [@EinfachHans](https://github.com/EinfachHans) I've already converted each function to be working with the signals, so both are working out of the box.
> > 
> > * getTranslations(language: string)
> > * getTranslation(key)
> > 
> > But they're returning a values/objects and not signals.
> > What I understand from you wish, is that `getSignal` returns a signal which is going to reflect the actual state of the targeted key. I'm not sure if it's a good idea, shall we open a discussion about it ?
> > My point is, to do so each key will need to be a signal. If you add 1000 words, then you're instantiating 1000 signals.
> > It could(will) have huge consequences on the optimisation end. _(To be analyzed)_ But, was that even possible in the former version of ngx-translate?
> > If that isn't the case, could you please open a new issue and clarify there, as good as possible, what you'd really like, and also the why ?
> 
> This is what `stream()`, the translate pipe and translate directive already do. Currently, the pipe & directive subscribe to 3 different signals. (langChange, fallbackLangChange and translationChange).

Yeh, also saw that on the pipe and directive, and it seemed like underoptimized. 

But this issue here is "only" about implementing similar way of working but with signals, that user could get down with the `$currentLang` and `$languages` as it was my specific need. 

I also believed it would set a good base for extending it with @EinfachHans & @floAtEbcont ideas, but in a separate issues. as I'd prefer "micro commit / pr" instead of big, breaking changes one '^^.

_But I'm open to anything, this PR shall also be dropped if deemed useless._

**Comment by rbalet** [comment]
> [@rbalet](https://github.com/rbalet) You only addressed `onTranslationChange`, but to be consistent, I think `get()` should have a signal equivalent too - here's a method that works for me:
> 
> class ExtendedTranslateService extends TranslateService {
>   translate(
>         key: string | Signal<string>,
>         params?: Record<string, string | number | null | undefined> | Signal<Record<string, string | number | null | undefined> | undefined>,
>     ): Signal<string | undefined> {
>         const key$ = toObservable(isSignal(key) ? key : signal(key));
>         const params$ = toObservable(isSignal(params) ? params : signal(params));
> 
>         const translation$ = key$.pipe(switchMap((key) => params$.pipe(switchMap((params) => this.get(key, params)))));
> 
>         return toSignal(translation$);
>    }
> }
> This can than be used like this for example:
> 
> class MyComponent {
>   readonly amount = computed(() => this.someComputation());
>   readonly someReactiveTranslation = this.extendedTranslateService.translate('myKey', computed(() => ({
>     amount: this.amount()
>   }));
> }

@floAtEbcont 

I'm not sure I understand why you're making it like that instead of the following porposition
```typescript
class MyComponent {
   readonly amount = computed(() => this.someComputation());
   readonly someReactiveTranslation =  computed(() => ({
      this.extendedTranslateService.translate('myKey', 
     amount: this.amount()
   }));
}
```

But I would understand the `getSignal` which I'll try to implement this week

**Comment by rbalet** [comment]
Hi 
@EinfachHans I've implemented the `$stream()` method : https://github.com/ngx-translate/core/blob/feat/signals/projects/ngx-translate/src/lib/translate.service.ts#L411

This will return a signal that will update himself on language change
It's simply using the steam observable under the hood, and can be call as follow 
```
    $textAsSignal = this.translate.$stream(
        "demo.simple.text-as-signal",
        {},
        { initialValue: "..." },
    );
```
----

@floAtEbcont I've dug deeper and this seems impossible, as you cannot use a `toSignal` inside a `computed`. I'm all ears if you have an idea here

**Comment by floAtEbcont** [comment]
@rbalet 

> I've dug deeper and this seems impossible, as you cannot use a toSignal inside a computed. I'm all ears if you have an idea here

I don't understand: Where did I propose to do that (put a `toSignal` inside a `computed`)? I wouldn't see the point in that, even if it were possible.

**Comment by rbalet** [comment]
@floAtEbcont Ok, I may have misunderstood this point and what you're trying to archive here then

<img width="807" height="466" alt="Image" src="https://github.com/user-attachments/assets/69059667-6a76-4618-8b6e-92d79432b331" />

**Comment by floAtEbcont** [comment]
@rbalet 
> Ok, I may have misunderstood this point and what you're trying to archive here then

If you look closely at your screenshot of [my code sample](https://github.com/ngx-translate/core/issues/1532#issuecomment-2729044551), the `toSignal` is _not inside_ a `computed`. It's kind of the other way round actually: The return value of a `computed` is passed to `toObservable`  (to be able to interact with ngx-translate's internal `get` method) and then a combined result of _that_ is passed on to `toSignal`. (And that works as far as I can tell - like I said, I'm already using this in production code.)

Here's a more verbose example of how one could use my wrapper and of what I would like ngx-translate to support out-of-the-box:

```typescript
class MyComponent {
  readonly translationKey = signal('myKey'); // could also be some `computed()`
  readonly interpolationParams = signal({ amount: 12 }); // could also be some `computed()`

  readonly translation = this.extendedTranslateService.translate(
    this.translationKey, 
    this.interpolationParams
  );
}
```

**Note:** As `translate` uses `toObservable` and `toSignal`, it _has_ to be called in a constructor context (just as any `computed`).

### Thoughts on implementation in ngx-translate

I haven't looked to deeply at the internals of ngx-translate. So while I'm pretty certain that just copying my wrapper method directly into `TranslateService` would _work_, it _might_ be a better option to do things the other way round:

Have the `TranslateStore` contain Signals (wrapping properties like [TranslateStore.translations](https://github.com/ngx-translate/core/tree/b0d76d0e8e8ea8fd426845d3bffab0095195f572/projects/ngx-translate/src/lib/translate.store.ts#L20)) and then use `toObservable` to wrap it for the legacy angular applications still using ngx-translate's observable methods. (That might be quite a big refactoring.)

If you _do_, however, end up choosing some version of my above signal wrapper `translate` method, it would require performance testing and maybe tuning. Also, it would be neat to give it an additional optional parameter allowing to pass in an alternate `injector` for `toSignal` and `toObservable`.

**Comment by CodeAndWeb** [comment]
https://github.com/ngx-translate/core/commit/3972d56b08e802b9626cc95c3f80828d71fc6444

I've added the function `translate` function with the suggested API.

I am still not sure if switching completely to signals makes things better or worse... I wanted to keep this as isolated as possible for now until the hierarchy logic is working (the newer changes).

In that change I introduced `onTranslationRefresh` which combines translation, language and fallbackLanguage changes. 
This already allows reducing the code in the Pipe and Directive - they registered for each change separately.
This is just an intermediate step. Internally, this updates a signal `refreshCounter` that can be used until we introduce the signals.

**Comment by CodeAndWeb** [comment]
I think the next logical step would be to convert `lang` and `fallbackLang` and `translations` to signals as @rbalet suggested and then use `toObservable` to maintain the 'old' API.

So the goal would be to switch to signals as soon as possible when the translations arrive from the http request.
